/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo_ed;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Pedro2
 */
public class AppEstrutura extends javax.swing.JFrame {

    /**
     * Creates new form AppEstrutura
     */
    public AppEstrutura() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Estruturas");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Lista sequencial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Fila sequencial");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Pilha");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem6.setText("Lista simplesmente encadeada");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem4.setText("Lista duplamente encadeada");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem7.setText("Arvore Binaria de Pesquisa");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String aux;
        int i = 0;
        //int tamanhoL = 0;
        ArrayList valor = new ArrayList();
        //Obtem um dado de entrada do teclado
        //String entrada = JOptionPane.showInputDialog("Digite 1 para desenhar retangulo\n 2 para desenhar oval\n");
        int tamanhoL = Integer.parseInt(JOptionPane.showInputDialog("Digite o tamaho da Fila: "));
        /*for(; i< tamanhoL;i++)
        {
            //= JOptionPane.showInputDialog("digite o valor a ser inserido: ");
            //aux = JOptionPane.showInputDialog("digite o valor a ser inserido na posiÃ§Ã£o: "+ (i+1));
            valor.add(i, "");
        }*/
        //Converte o valor digitado de String para Inteiro
        int choice = 2; //Integer.parseInt(entrada);
        
        
        
        //Cria um objeto do tipo RetangOval e passa o choice como parametro para o construtor
        RetangOval ro = new RetangOval(choice, tamanhoL);
        
        
        //Criando a janela de exibiÃ§Ã£o
        JFrame jf = new JFrame();
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.add(ro); //Adiciona o objeto jo ao jframe
        jf.setSize(500,500);
        //jPanel1.add(jf);
        jf.setVisible(true);
        FormFilaSeq item2 = new FormFilaSeq(ro,jf,tamanhoL);
        pack();
        jDesktopPane1.add(item2);
        item2.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String aux;
        int i = 0;
        //int tamanhoL = 0;
        ArrayList valor = new ArrayList();
        //Obtem um dado de entrada do teclado
        //String entrada = JOptionPane.showInputDialog("Digite 1 para desenhar retangulo\n 2 para desenhar oval\n");ionn
        int tamanhoL = 0;
        try{
            tamanhoL = Integer.parseInt(JOptionPane.showInputDialog("Digite o tamaho da lista: "));
        } catch (NumberFormatException n){
            JOptionPane.showMessageDialog(AppEstrutura.this, "Digite o tamanho da lista!","ERRO", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
       for(; i< tamanhoL;i++)
        {
            //= JOptionPane.showInputDialog("digite o valor a ser inserido: ");
            //aux = JOptionPane.showInputDialog("digite o valor a ser inserido na posiÃ§Ã£o: "+ (i+1));
            valor.add(i, "");
        }
        //Converte o valor digitado de String para Inteiro
        int choice = 2; //Integer.parseInt(entrada);
        
        
        
        //Cria um objeto do tipo RetangOval e passa o choice como parametro para o construtor
        RetangOval ro = new RetangOval(choice, tamanhoL);
        
        
        //Criando a janela de exibiÃ§Ã£o
        JFrame jf = new JFrame();
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.add(ro); //Adiciona o objeto jo ao jframe
        jf.setSize(500,500);
        //jPanel1.add(jf);
        jf.setVisible(true);
        FormListaSeq item1 = new FormListaSeq(ro, jf, tamanhoL);
        pack();
        jDesktopPane1.add(item1);
        item1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        String aux;
        int i = 0;
        //int tamanhoL = 0;
        ArrayList valor = new ArrayList();
        //Obtem um dado de entrada do teclado
        //String entrada = JOptionPane.showInputDialog("Digite 1 para desenhar retangulo\n 2 para desenhar oval\n");
        int tamanhoL = Integer.parseInt(JOptionPane.showInputDialog("Digite o tamanho da Pilha: "));
        for(; i< tamanhoL;i++)
        {
            //= JOptionPane.showInputDialog("digite o valor a ser inserido: ");
            //aux = JOptionPane.showInputDialog("digite o valor a ser inserido na posiÃ§Ã£o: "+ (i+1));
            valor.add(i, "");
        }
        //Converte o valor digitado de String para Inteiro
        int choice = 2; //Integer.parseInt(entrada);
        
        
        
        //Cria um objeto do tipo RetangOval e passa o choice como parametro para o construtor
        DesenhaPilha ro = new DesenhaPilha(choice, tamanhoL);
        
        
        //Criando a janela de exibiÃ§Ã£o
        JFrame jf = new JFrame();
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.add(ro); //Adiciona o objeto jo ao jframe
        jf.setSize(640,680);
        //jPanel1.add(jf);
        jf.setVisible(true);
        FormPilhaSeqTeste item1 = new FormPilhaSeqTeste(ro, jf, tamanhoL);
        pack();
        jDesktopPane1.add(item1);
        item1.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed



        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       // this.contador = 0;
        DesenhaListaDEnc ro = new DesenhaListaDEnc(contador);
        JFrame jf = new JFrame();
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.add(ro); //Adiciona o objeto jo ao jframe
        jf.setSize(900, 300);
        jf.setLocation(420,0);
       // jPanel1.add(jf);
        jf.setVisible(true);
        FormListaDEnc item2 = new FormListaDEnc(ro, jf);
        jDesktopPane1.add(item2);
        pack();
        
        item2.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        DesenhaListaSEnc ro = new DesenhaListaSEnc(contador);
        JFrame jf = new JFrame();
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.add(ro); //Adiciona o objeto jo ao jframe
        jf.setSize(900,300);
        jf.setLocation(420,0);
        // jPanel1.add(jf);
        jf.setVisible(true);
        FormListaSEnc item2 = new FormListaSEnc(ro, jf);
        jDesktopPane1.add(item2);
        pack();
        
        item2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        DesenhaArvore ro = new DesenhaArvore();
        JFrame jf = new JFrame();
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.add(ro); //Adiciona o objeto jo ao jframe
        jf.setSize(900, 400);
        jf.setLocation(420,0);
        // jPanel1.add(jf);
        jf.setVisible(true);
        FormABP item2 = new FormABP(ro, jf);
        jDesktopPane1.add(item2);
        pack();
        
        item2.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppEstrutura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppEstrutura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppEstrutura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppEstrutura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppEstrutura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
int contador = 0;

}
