/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo_ed;

import exemplo_ed.DesenhaListaSEnc;
import exemplo_ed.DesenhaListaSEnc;
import exemplo_ed.DesenhaListaSEnc;
import exemplo_ed.LSE;
import exemplo_ed.LSE;
import exemplo_ed.LSE;
import exemplo_ed.teste;
import exemplo_ed.teste;
import exemplo_ed.teste;
import java.awt.Point;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class FormListaSEnc extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormListaSEnc
     */
    public FormListaSEnc(DesenhaListaSEnc ro, JFrame jf) {
        this.minhaLista = new LSE();
        this.ox = new JLabel[contador];
        this.ro = ro;
        this.jf = jf;
        //ro = new DesenhaListaSEnc(contador);
        dados = new LinkedList();
        
        int x = 19, h = 15;
        
        for(int j = 0; j <= 17; j++)
        {
            Point p = new Point(x, h);
            JLabel test = new JLabel("");
            test.setOpaque(true);
            this.jf.add(test);
            test.setSize(20, 20);
            test.setLocation(p);

            if(j == 17)
            {
                //test.setText("safado");
                test.setVisible(false);
            }
            else
                test.setVisible(true);
            dados.add(test);
            test.setText("");
            
            x += 50;
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Conteudo:");

        jLabel2.setText("Posicao:");

        jLabel3.setText("Posicao:");

        jLabel4.setText("(Campo opcional)");

        jToggleButton1.setText("Busca");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Elemento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        contador++;
        ro = new DesenhaListaSEnc(contador);
        jf.add(this.ro);            
        jf.setVisible(true);       
        jf.repaint();
        
        int dado, pos;
        JLabel aux;
        
        dado = Integer.parseInt(jTextField1.getText());
        
        if(jTextField3.getText().equals(""))
        {
            minhaLista.insere(contador, dado);
            aux = dados.get(contador - 1);
            aux.setText(dado + "");
        }
        else
        {
            pos = Integer.parseInt(jTextField3.getText());
            if(pos <= minhaLista.tamanho() + 1 && pos > 0)
            {
                aux = dados.get(pos - 1);
                if(minhaLista.elemento(pos) != 0)
                {
                    boolean ret;
                    ret = minhaLista.insere(pos, dado);
                    if(ret)
                    {
                        for (int i = minhaLista.tamanho(); i >= pos; i--)
                        {
                            dados.get(i).setText(dados.get(i - 1).getText());
                        }    
                    aux.setText(minhaLista.elemento(pos) + "");
                    }
                else
                    JOptionPane.showMessageDialog(FormListaSEnc.this, "Inserção falhou!","ERRO", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
                JOptionPane.showMessageDialog(FormListaSEnc.this, "Inserção falhou!","ERRO", JOptionPane.INFORMATION_MESSAGE);
        }
        
        jTextField3.setText("");
        jTextField1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int pos = Integer.parseInt(jTextField2.getText());
        if(!jTextField2.getText().equals("") && pos > 0 && pos <= minhaLista.tamanho())
        {
            jf.setVisible(false);
            if (contador == 0){
                contador++;
                JOptionPane.showMessageDialog(FormListaSEnc.this, "Remocao falhou! A Lista esta vazia!","ERRO", JOptionPane.INFORMATION_MESSAGE);
             
            }
            contador--;
        
            jf = new JFrame();
            ro = new DesenhaListaSEnc(contador);
            jf.add(this.ro);
            jf.repaint();
            jf.setSize(900,300);
            jf.setLocation(420,0);
            jf.setVisible(true);
        
            for(int i = 0; i <= 17; i++)
            {
                jf.add(dados.get(i));
            }
                

            JLabel aux;
            pos = Integer.parseInt(jTextField2.getText());
            if(!jTextField2.getText().equals("") && !minhaLista.vazia() && pos <= minhaLista.tamanho())
            {
                int rem;
                for (int i = pos - 1; i < minhaLista.tamanho() - 1; i++)
                {
                    dados.get(i).setText(dados.get(i+1).getText());
                }
                dados.get(minhaLista.tamanho() - 1).setText("");
                rem = minhaLista.remove(pos);
                if(rem == -1)
                    JOptionPane.showMessageDialog(FormListaSEnc.this, "Falha ao remover!","ERRO", JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(FormListaSEnc.this, "Removido o elemento: " + rem + "!","Removido", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(FormListaSEnc.this, "Remocao falhou! Posicao informada invalida!","ERRO", JOptionPane.INFORMATION_MESSAGE);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        int dado , res;
        dado = Integer.parseInt(jTextField4.getText());
        if(!jTextField4.getText().equals("") && !minhaLista.vazia())
        {
            res = minhaLista.posicao(dado);
            if(res == -1)
            JOptionPane.showMessageDialog(FormListaSEnc.this, "O elemento pesquisado nao esta na lista!","ERRO", JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(FormListaSEnc.this, "O elemento " + dado + " esta na posicao: " + res,"Encontrado", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        JOptionPane.showMessageDialog(FormListaSEnc.this, "Lista vazia ou campo de elemento vazio!","ERRO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
    
    JFrame jf;
    DesenhaListaSEnc ro,ko ;
    int contador = 0;
    int tamanho;
    LinkedList <JLabel> dados;
    JLabel[] ox;
    teste t;
    //Graphics g;
    int aux = 0;
    LSE minhaLista;
    

}
