/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo_ed;

import exemplo_ed.DesenhaListaDEnc;
import exemplo_ed.DesenhaListaDEnc;
import exemplo_ed.DesenhaListaDEnc;
import exemplo_ed.LDE;
import exemplo_ed.LDE;
import exemplo_ed.LDE;
import exemplo_ed.teste;
import exemplo_ed.teste;
import exemplo_ed.teste;
import java.awt.Graphics;
import java.awt.Point;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Luciano
 */
public class FormListaDEnc extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormListaEnc
     */
    public FormListaDEnc(DesenhaListaDEnc ro, JFrame jf) {
        this.minhaLista = new LDE();
        this.ox = new JLabel[contador];
        this.ro = ro;
        this.jf = jf;
        //ro = new DesenhaListaDEnc(contador);
        // int contador = 0;
        
        dados = new LinkedList();
        
        int x = 19, h = 15;
        
        for(int j = 0; j <= 17; j++)
        {
            Point p = new Point(x, h);
            JLabel test = new JLabel("");
            test.setOpaque(true);
            this.jf.add(test);
            test.setSize(20, 20);
            test.setLocation(p);

            if(j == 17)
            {
                //test.setText("safado");
                test.setVisible(false);
            }
            else
                test.setVisible(true);
            dados.add(test);
            test.setText("");
            
            x += 50;
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("Conteudo:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Posicao:");

        jLabel3.setText("Posicao:");

        jLabel4.setText("(Campo opcional)");

        jLabel5.setText("Elemento:");

        jButton3.setText("Busca");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton3))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        contador++;
        ro = new DesenhaListaDEnc(contador);
        jf.add(this.ro);
        jf.setVisible(true);
        jf.repaint();
         
        int dado, pos;
        JLabel aux;
        
        dado = Integer.parseInt(jTextField1.getText());
        
        if(jTextField3.getText().equals(""))
        {
            minhaLista.insere(contador, dado);
            aux = dados.get(contador - 1);
            aux.setText(dado + "");
        }
        else
        {
            pos = Integer.parseInt(jTextField3.getText());
            if(pos <= minhaLista.tamanho() + 1 && pos > 0)
            {
                aux = dados.get(pos - 1);
                if(minhaLista.elemento(pos) != 0)
                {
                    boolean ret;
                    ret = minhaLista.insere(pos, dado);
                    if(ret)
                    {
                        for (int i = minhaLista.tamanho(); i >= pos; i--)
                        {
                            dados.get(i).setText(dados.get(i - 1).getText());
                        }    
                    aux.setText(minhaLista.elemento(pos) + "");
                    }
                else
                    JOptionPane.showMessageDialog(FormListaDEnc.this, "Inserção falhou!","ERRO", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
                JOptionPane.showMessageDialog(FormListaDEnc.this, "Inserção falhou!","ERRO", JOptionPane.INFORMATION_MESSAGE);
        }
        
        jTextField3.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int pos = Integer.parseInt(jTextField2.getText());
        if(!jTextField2.getText().equals("") && pos > 0 && pos <= minhaLista.tamanho())
        {    
            jf.setVisible(false);
            if (contador == 0){
                contador++;
                JOptionPane.showMessageDialog(FormListaDEnc.this, "Inserção falhou! A Lista esta vazia!","ERRO", JOptionPane.INFORMATION_MESSAGE);
             
            }
            contador--;
        
            jf = new JFrame();
            ro = new DesenhaListaDEnc(contador);
            jf.add(this.ro);
            jf.repaint();
            jf.setSize(900, 300);
            jf.setLocation(420,0);
            jf.setVisible(true);
            
            for(int i = 0; i <= 17; i++)
            {
                jf.add(dados.get(i));
            }
                

            JLabel aux;
            pos = Integer.parseInt(jTextField2.getText());
            if(!jTextField2.getText().equals("") && !minhaLista.vazia() && pos <= minhaLista.tamanho())
            {
                int rem;
                for (int i = pos - 1; i < minhaLista.tamanho() - 1; i++)
                {
                    dados.get(i).setText(dados.get(i+1).getText());
                }
                dados.get(minhaLista.tamanho() - 1).setText("");
                rem = minhaLista.remove(pos);
                if(rem == -1)
                    JOptionPane.showMessageDialog(FormListaDEnc.this, "Falha ao remover!","ERRO", JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(FormListaDEnc.this, "Removido o elemento: " + rem + "!","Removido", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(FormListaDEnc.this, "Remocao falhou! Posicao informada invalida!","ERRO", JOptionPane.INFORMATION_MESSAGE);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int dado , res;
        dado = Integer.parseInt(jTextField4.getText());
        if(!jTextField4.getText().equals("") && !minhaLista.vazia())
        {
            res = minhaLista.posicao(dado);
            if(res == -1)
            JOptionPane.showMessageDialog(FormListaDEnc.this, "O elemento pesquisado nao esta na lista!","ERRO", JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(FormListaDEnc.this, "O elemento " + dado + " esta na posicao: " + res,"Encontrado", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        JOptionPane.showMessageDialog(FormListaDEnc.this, "Lista vazia ou campo de elemento vazio!","ERRO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
   
    JFrame jf;
    DesenhaListaDEnc ro,ko ;
    int contador = 0;
    int tamanho;
    LinkedList <JLabel> dados;
    JLabel[] ox;
    teste t;
    //Graphics g;
    int aux = 0;
    LDE minhaLista;
}
