/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo_ed;

import java.awt.Point;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Luciano
 */
public class FormPilhaSeqTeste extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPilhaSeq
     */
   public FormPilhaSeqTeste(DesenhaPilha ro, JFrame jf, int tamanho) {
        initComponents();
        this.ro = ro;
        this.jf = jf;
        this.tamanho = tamanho;
        minhapilha = new PilhaSeq(this.tamanho);
        dados = new LinkedList();
        int h = 13;
        int x = 294;
        
        for(int j = 0; j <= tamanho; j++)
        {
            Point p = new Point(x, h);
            JLabel test = new JLabel();
            this.jf.add(test);
            test.setOpaque(true);
            test.setSize(30, 20);
            test.setText("");
            test.setLocation(p);

            h = h + 30;

            dados.add(test);
            if(j == tamanho)
            {
                //test.setText("safado");
                test.setVisible(false);
            }
            else
                test.setVisible(true);   
            
            test.setText("");
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Conteudo: ");

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int pos, dado;
        JLabel aux;

        //String dado;
        pos = minhapilha.tamanho() - (minhapilha.tamanho() - 1);
        dado = Integer.parseInt(jTextField2.getText());
        //aux = dados.get(tamanho - minhapilha.tamanho() - 1);
        if( !jTextField2.getText().equals("") && !minhapilha.cheia() && minhapilha.tamanho() <= tamanho)
        {
            aux = dados.get(tamanho - minhapilha.tamanho() - 1);
            if(minhapilha.top() != 0)
            {
                boolean ret;
                ret = minhapilha.push(dado);
                if(ret)
                {
                    aux.setText(minhapilha.top()+"");
                    pos++;
                }
                else
                    JOptionPane.showMessageDialog(FormPilhaSeqTeste.this, "Insercao falhou!","ERRO", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                minhapilha.push(dado);
                aux.setText(minhapilha.top() + "");
                aux.setVisible(true);
            }
        }
        else
            JOptionPane.showMessageDialog(FormPilhaSeqTeste.this, "Lista cheia ou campos vazios!","ERRO", JOptionPane.INFORMATION_MESSAGE);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        // TODO add your handling code here:
        if(!minhapilha.vazia())
        {
            int ret = minhapilha.pop();
            dados.get(tamanho - minhapilha.tamanho() - 1).setText("");
            JOptionPane.showMessageDialog(FormPilhaSeqTeste.this, "Dado removido: " + ret + "!","REMOVIDO", JOptionPane.INFORMATION_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(FormPilhaSeqTeste.this, "Remocao falhou! A pilha esta vazia!","ERRO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

 PilhaSeq minhapilha;
 JFrame jf; 
 DesenhaPilha ro;
 int tamanho;
 LinkedList<JLabel> dados;
 javax.swing.JTextField jTextField1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
